# Generated by Django 5.2.6 on 2025-09-30 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_codeforces_handle_user_leetcode_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='div',
            field=models.CharField(choices=[('Div. 1', 'Div. 1'), ('Div. 2', 'Div. 2'), ('Community', 'Community')], default='Div. 2', max_length=10),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_rating', models.IntegerField(default=1500)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
