# Generated by Django 5.2.6 on 2025-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='durationSeconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='phase',
            field=models.CharField(default='FINISHED', max_length=50),
        ),
        migrations.AddField(
            model_name='contest',
            name='preparedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='startTimeSeconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='problemResults',
            field=models.JSONField(default=dict),
        ),
    ]
