# Generated by Django 5.2.6 on 2025-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_contest_contest_id_contest_durationseconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('Div. 1', 'Div. 1'), ('Div. 2', 'Div. 2'), ('Community', 'Community')], default='Div. 2', max_length=50),
        ),
    ]
