# Generated by Django 5.2.6 on 2025-10-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_div_team'),
        ('cp', '0003_contest_contest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='participant_type',
            field=models.CharField(choices=[('Contestant', 'Contestant'), ('OutOfCompetition', 'OutOfCompetition'), ('Virtual', 'Virtual'), ('Practice', 'Practice')], default='Contestant', max_length=50),
        ),
        migrations.AlterField(
            model_name='standing',
            name='problemResults',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='TeamRanklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_solved', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1500)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_solved', models.IntegerField(default=0)),
                ('penalty_time', models.IntegerField(default=0)),
                ('problemResults', models.JSONField(default=list)),
                ('rating_change', models.IntegerField(default=0)),
                ('participant_type', models.CharField(choices=[('Contestant', 'Contestant'), ('OutOfCompetition', 'OutOfCompetition'), ('Virtual', 'Virtual'), ('Practice', 'Practice')], default='Contestant', max_length=50)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.contest')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
