# Generated by Django 5.2.6 on 2025-10-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0004_standing_participant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
