# Generated by Django 5.2.6 on 2025-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0005_standing_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
