# Generated by Django 5.2.6 on 2025-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0006_standing_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstanding',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
